name: Auto message for PR's and Issues
description: Automatically send hello message to the first PR and Issue for new contributor.
branding:
  icon: message-square
  color: yellow
on: [pull_request, issues]
jobs:
  build:
    name: Hello new contributor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Hey, thank you for opening your first Issue ! 🚀 Feel free to add assignees and tags. Also don't forget to read our README.md for contribution guidelines!"
          pr-message: "Hey, thank you for opening your first Pull Request ! 🚀 Don't forget to read our README.md for contribution guidelines"
